# Site settings
course_name: MECH230 Dynamics
course_description: "In this course, we get introduced to Euler's first and second laws 
(the balance of linear and angular momentum), and apply them to particles, 
system of particles, and rigid bodies in planar motion."
course_semester: "Spring 2025"

# baseurl: "/ml4science/" # the subpath of your site, e.g. /blog/
# url: "http://josephbakarji.github.io/" # the base hostname & protocol for your site

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mech230.github.io" # the base hostname & protocol for your site

schoolname: "American University of Beirut"
schoolurl: "https://www.aub.edu.lb"
twitter_username: josephbakarji 

address: |
    American University of Beirut
    P.O.Box 11-0236 / Mechanical Engineering
    Riad El-Solh / Beirut 1107 2020

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
